import type {
  Term,
  IriTerm,
  QuadTerm,
  BlankTerm,
  LiteralTerm,
  VariableTerm,
  Tuple,
  Wildcard,
  Variable,
  Expression,
  BaseExpression,
  VariableExpression,
  AggregateExpression,
  OperationExpression,
  FunctionCallExpression,
  Pattern,
  Triple,
  BgpPattern,
  GroupPattern,
  UnionPattern,
  BlockPattern,
  GraphPattern,
  MinusPattern,
  ServicePattern,
  OptionalPattern,
  BindPattern,
  FilterPattern,
  ValuesPattern,
  ValuePatternRow,
  Query,
  Update,
  SparqlQuery,
  BaseQuery,
  AskQuery,
  SelectQuery,
  DescribeQuery,
  ConstructQuery,
  UpdateOperation,
  LoadOperation,
  CreateOperation,
  ClearDropOperation,
  ManagementOperation,
  CopyMoveAddOperation,
  InsertDeleteOperation,
  Grouping,
  Ordering,
  PropertyPath,
  NegatedPropertySet,
  SparqlParser,
  ParserOptions,
  SparqlGenerator,
  GeneratorOptions,
  Quads,
  GraphQuads,
  GraphOrDefault,
  GraphReference,
} from 'sparqljs';

export type PropertySet = Exclude<PropertyPath, NegatedPropertySet>;

export type PatternOrTriple = Pattern | Triple;
export type TermOrPrimitive = Term | number | string | bigint | boolean;
export type ExpressionOrPrimitive =
  | Expression
  | number
  | string
  | bigint
  | boolean;

export {
  Term,
  IriTerm,
  QuadTerm,
  BlankTerm,
  LiteralTerm,
  VariableTerm,
  Tuple,
  Wildcard,
  Variable,
  Expression,
  BaseExpression,
  VariableExpression,
  AggregateExpression,
  OperationExpression,
  FunctionCallExpression,
  Pattern,
  Triple,
  BgpPattern,
  GroupPattern,
  UnionPattern,
  BlockPattern,
  GraphPattern,
  MinusPattern,
  ServicePattern,
  OptionalPattern,
  BindPattern,
  FilterPattern,
  ValuesPattern,
  ValuePatternRow,
  Query,
  Update,
  SparqlQuery,
  BaseQuery,
  AskQuery,
  SelectQuery,
  DescribeQuery,
  ConstructQuery,
  UpdateOperation,
  LoadOperation,
  CreateOperation,
  ClearDropOperation,
  ManagementOperation,
  CopyMoveAddOperation,
  InsertDeleteOperation,
  Grouping,
  Ordering,
  PropertyPath,
  NegatedPropertySet,
  SparqlParser,
  ParserOptions,
  SparqlGenerator,
  GeneratorOptions,
  Quads,
  GraphQuads,
  GraphOrDefault,
  GraphReference,
};
