name: publish
on:
  release:
    types:
      - published

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: BUild the package
        run: pnpm run build

      - name: Install dependencies
        run: pnpm run build

      - name: Install dependencies
        run: pnpm publish --tag beta
